const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Workout = require('../models/workoutModel');

dotenv.config({ path: './config.env' });

const DB = process.env.DATABASE.replace('<PASSWORD>', process.env.DATABASE_PASSWORD);

mongoose
  .connect(DB, {
    // Options to deal with deprecation warnings.
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
    useUnifiedTopology: true,
  })
  .then(() => console.log('DB connection successful!'));

const workoutSeed = [
  // Day 1 + UPPER 1----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 1)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 20,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Bench Press',
        duration: 8,
        weight: 100,
        reps: 4,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Bent Over Press',
        duration: 8,
        weight: 100,
        reps: 4,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shoulder Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lat Pulldown',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Low Cable Crossovers',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Triceps Extension',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Rope Cable Face Pulls',
        duration: 8,
        weight: 100,
        reps: 11,
        sets: 2,
      },
    ],
  },

  // Day 2 + lower 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 2)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 21,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Squat',
        duration: 8,
        weight: 100,
        reps: 4,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Glute Ham Raise',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lunge',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lying Leg Curl',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Standing Calf Raise',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
    ],
  },
  // Day 4 + Upper 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 4)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 20,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Pull Up',
        duration: 8,
        weight: 100,
        reps: 4,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Incline Bench Press',
        duration: 8,
        weight: 100,
        reps: 4,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Cable Straight Arm Pulldown',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Up',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Triceps Kickback',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
    ],
  },
  // Day 5 + Lower 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 5)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 19,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Leg Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Romanian Deadlift',
        duration: 8,
        weight: 100,
        reps: 4,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shrug',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Leg Extensions',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Seated Calf Raise',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 4,
      },
      {
        type: 'Resistance',
        name: 'Hanging Leg Raise',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 4,
      },
    ],
  },

  // Day 7 + Upper 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 7)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 18,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Bench Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Bent Over Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shoulder Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lat Pulldown',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Low Cable Crossovers',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Triceps Extension',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Rope Cable Face Pulls',
        duration: 8,
        weight: 100,
        reps: 13,
        sets: 2,
      },
    ],
  },
  // Day 8 + Lower 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 8)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 18,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Squat',
        duration: 8,
        weight: 100,
        reps: 4,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Glute Ham Raise',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lunge',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lying Leg Curl',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Standing Calf Raise',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
    ],
  },

  // Day 10 + Upper 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 10)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 17,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Pull Up',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Incline Bench Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Cable Straight Arm Pulldown',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Up',
        duration: 8,
        weight: 100,
        reps: 11,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Triceps Kickback',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
    ],
  },

  // Day 11 + Lower 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 11)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 17,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Leg Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Romanian Deadlift',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shrug',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Leg Extensions',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Seated Calf Raise',
        duration: 8,
        weight: 100,
        reps: 11,
        sets: 4,
      },
      {
        type: 'Resistance',
        name: 'Hanging Leg Raise',
        duration: 8,
        weight: 100,
        reps: 11,
        sets: 4,
      },
    ],
  },

  // Day 13 + Upper 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 13)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 15,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Bench Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Bent Over Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shoulder Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lat Pulldown',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Low Cable Crossovers',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Triceps Extension',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Rope Cable Face Pulls',
        duration: 8,
        weight: 100,
        reps: 14,
        sets: 2,
      },
    ],
  },
  // Day 14 + Lower 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 14)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 16,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Squat',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Glute Ham Raise',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lunge',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lying Leg Curl',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Standing Calf Raise',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
    ],
  },
  // Day 16 + Upper 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 16)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 17,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Pull Up',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Incline Bench Press',
        duration: 8,
        weight: 100,
        reps: 5,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Cable Straight Arm Pulldown',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Up',
        duration: 8,
        weight: 100,
        reps: 11,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Triceps Kickback',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
    ],
  },

  // Day 17 + Lower 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 17)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 15,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Leg Press',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Romanian Deadlift',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shrug',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Leg Extensions',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Seated Calf Raise',
        duration: 8,
        weight: 100,
        reps: 13,
        sets: 4,
      },
      {
        type: 'Resistance',
        name: 'Hanging Leg Raise',
        duration: 8,
        weight: 100,
        reps: 13,
        sets: 4,
      },
    ],
  },
  // Day 18 + Upper 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 18)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 14,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Bench Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Bent Over Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shoulder Press',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lat Pulldown',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Low Cable Crossovers',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Triceps Extension',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Rope Cable Face Pulls',
        duration: 8,
        weight: 100,
        reps: 15,
        sets: 2,
      },
    ],
  },

  // Day 20 + Lower 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 20)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 15,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Squat',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Glute Ham Raise',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lunge',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lying Leg Curl',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Standing Calf Raise',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
    ],
  },

  // Day 21 + Upper 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 21)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 14,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Pull Up',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Incline Bench Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Press',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Cable Straight Arm Pulldown',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Up',
        duration: 8,
        weight: 100,
        reps: 12,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Triceps Kickback',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
    ],
  },

  // Day 22 + Lower 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 22)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 13,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Leg Press',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Romanian Deadlift',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shrug',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Leg Extensions',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Seated Calf Raise',
        duration: 8,
        weight: 100,
        reps: 13,
        sets: 4,
      },
      {
        type: 'Resistance',
        name: 'Hanging Leg Raise',
        duration: 8,
        weight: 100,
        reps: 13,
        sets: 4,
      },
    ],
  },
  // Day 24 + Upper 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 24)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 14,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Bench Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Bent Over Press',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shoulder Press',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lat Pulldown',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Low Cable Crossovers',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Triceps Extension',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Rope Cable Face Pulls',
        duration: 8,
        weight: 100,
        reps: 16,
        sets: 2,
      },
    ],
  },
  // Day 25 + Lower 1 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 25)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 13,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Squat',
        duration: 8,
        weight: 100,
        reps: 6,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Glute Ham Raise',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lunge',
        duration: 8,
        weight: 100,
        reps: 10,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Lying Leg Curl',
        duration: 8,
        weight: 100,
        reps: 10,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Standing Calf Raise',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
    ],
  },

  // Day 27 + Upper 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 27)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 13,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Pull Up',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Incline Bench Press',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Press',
        duration: 8,
        weight: 100,
        reps: 8,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Cable Straight Arm Pulldown',
        duration: 8,
        weight: 100,
        reps: 10,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Push Up',
        duration: 8,
        weight: 100,
        reps: 14,
        sets: 2,
      },
      {
        type: 'Resistance',
        name: 'Bicep Curl',
        duration: 8,
        weight: 100,
        reps: 10,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Triceps Kickback',
        duration: 8,
        weight: 100,
        reps: 10,
        sets: 3,
      },
    ],
  },
  // Day 28 + Upper 2 ----------------------------------------------------------------------
  {
    day: new Date(new Date().setDate(new Date().getDate() - 28)),
    exercises: [
      {
        type: 'Cardio',
        name: 'Running',
        duration: 13,
        distance: 1,
      },
      {
        type: 'Resistance',
        name: 'Leg Press',
        duration: 8,
        weight: 100,
        reps: 9,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Romanian Deadlift',
        duration: 8,
        weight: 100,
        reps: 7,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Shrug',
        duration: 8,
        weight: 100,
        reps: 11,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Leg Extensions',
        duration: 8,
        weight: 100,
        reps: 11,
        sets: 3,
      },
      {
        type: 'Resistance',
        name: 'Seated Calf Raise',
        duration: 8,
        weight: 100,
        reps: 15,
        sets: 4,
      },
      {
        type: 'Resistance',
        name: 'Hanging Leg Raise',
        duration: 8,
        weight: 100,
        reps: 15,
        sets: 4,
      },
    ],
  },
];

// SEED DB TO ATLAS
const seedData = async () => {
  try {
    await Workout.deleteMany();
    await Workout.create(workoutSeed);
    console.log(`Database successfully loaded with ${await Workout.countDocuments()} records`);
  } catch (err) {
    console.log(err);
  }
  process.exit();
};

seedData();
